version: 0.{build}
os: Windows Server 2012 R2
environment:
  COVERITY_TOKEN:
    secure: FOpEHWVcvSr8cX1ApUOVVkw6ds+9dcSF381tt/YTuB0=
  COVERITY_EMAIL:
    secure: UEqRjr6WeJQzmybaDQ1x8vGceHZcnwS/K67lMvLKaiE=
  COVERALLS_REPO_TOKEN:
    secure: QDrEvPQa9oEzLz7MU477Y4VDEj0NWGv5w08hr+Jv3kxZSUiStqF96yeofnuR1WkC
cache:
- src\packages -> **\packages.config
- C:\ProgramData\chocolatey\bin -> build.environment.ps1
- C:\ProgramData\chocolatey\lib -> build.environment.ps1
install:
- ps: .\build.environment.ps1
- ps: psake .\build.tasks.ps1 appveyor-install
build_script:
- ps: psake .\build.tasks.ps1 appveyor-build
test_script:
- ps: psake .\build.tasks.ps1 appveyor-test
artifacts:
- path: PublishCoverity.*.zip
- path: PublishCoverity.*.nupkg
deploy:
- provider: GitHub
  release: $($env:GitVersion_SemVer)
  auth_token:
    secure: hH6A9i7v+sf5mZy9FLQVG7n4UpLWkUhpshIsia7sGi1ONr+iMKroqjkJk0Hsi3nK
  artifact: /.*\.nupkg/
  prerelease: true
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: 4XLKYHbHXYJuc9SCTYZt5VzxE/XDBpjWSttRIK3ZGux5TwIgAnhMBamo16fjVmzS
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
